# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_text', models.CharField(max_length=255)),
                ('Score', models.IntegerField()),
            ],
        ),
    ]
