# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='TotalScores',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
