# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_user_totalscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
